# Generated by Django 4.0.3 on 2022-04-24 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Updatesource',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('model', models.CharField(blank=True, max_length=50, null=True)),
                ('datasource', models.CharField(blank=True, db_column='dataSource', max_length=50, null=True)),
            ],
            options={
                'db_table': 'UpdateSource',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.TextField(blank=True, choices=[('DIỆT MEN', 'DIỆT MEN'), ('SAO CHÈ', 'SAO CHÈ')], default='SẤY CHÈ', null=True)),
                ('time_start', models.TimeField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('config_name', models.CharField(blank=True, max_length=255, null=True)),
                ('tea_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
        migrations.CreateModel(
            name='DataCollect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.IntegerField(blank=True, null=True)),
                ('humid', models.IntegerField(blank=True, null=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('config_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_id_data', to='Home.config')),
            ],
        ),
        migrations.CreateModel(
            name='ConfigData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_min', models.IntegerField(blank=True, null=True)),
                ('temp_max', models.IntegerField(blank=True, null=True)),
                ('length', models.IntegerField(blank=True, null=True)),
                ('speed', models.IntegerField(blank=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('config_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_id', to='Home.config')),
            ],
        ),
    ]
